name: Publish @rbxts/localize
on:
    workflow_dispatch: null
    push:
        tags: ['*']

permissions:
    contents: read
    id-token: write

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest
                  run_install: false # We will run `pnpm install` ourselves
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  cache: pnpm
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'
            - name: Install Dependencies
              run: pnpm install --frozen-lockfile
            - name: Publish
              run: pnpm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
